/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatDotRound: typeof import('@element-plus/icons-vue')['ChatDotRound']
    Check: typeof import('@element-plus/icons-vue')['Check']
    DataAnalysis: typeof import('@element-plus/icons-vue')['DataAnalysis']
    Document: typeof import('@element-plus/icons-vue')['Document']
    House: typeof import('@element-plus/icons-vue')['House']
    InfoFilled: typeof import('@element-plus/icons-vue')['InfoFilled']
    Magic: typeof import('@element-plus/icons-vue')['Magic']
    Minus: typeof import('@element-plus/icons-vue')['Minus']
    Monitor: typeof import('@element-plus/icons-vue')['Monitor']
    Plus: typeof import('@element-plus/icons-vue')['Plus']
    Refresh: typeof import('@element-plus/icons-vue')['Refresh']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('@element-plus/icons-vue')['Setting']
    Tools: typeof import('@element-plus/icons-vue')['Tools']
    ElButton: typeof import('element-plus')['ElButton']
    ElCard: typeof import('element-plus')['ElCard']
    ElCol: typeof import('element-plus')['ElCol']
    ElContainer: typeof import('element-plus')['ElContainer']
    ElFooter: typeof import('element-plus')['ElFooter']
    ElForm: typeof import('element-plus')['ElForm']
    ElFormItem: typeof import('element-plus')['ElFormItem']
    ElHeader: typeof import('element-plus')['ElHeader']
    ElIcon: typeof import('element-plus')['ElIcon']
    ElInput: typeof import('element-plus')['ElInput']
    ElMain: typeof import('element-plus')['ElMain']
    ElMenu: typeof import('element-plus')['ElMenu']
    ElMenuItem: typeof import('element-plus')['ElMenuItem']
    ElRow: typeof import('element-plus')['ElRow']
    ElStatistic: typeof import('element-plus')['ElStatistic']
    ElSteps: typeof import('element-plus')['ElSteps']
    ElStep: typeof import('element-plus')['ElStep']
    ElTag: typeof import('element-plus')['ElTag']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    DefaultLayout: typeof import('./src/layouts/DefaultLayout.vue')['default']
  }
}